name: e2e

on:
  push:
    branches: [master, e2e]
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - 'template.config.js'

jobs:
  android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Prepare
        run: brew install imagemagick

      - name: Install repo dependencies
        run: yarn install --frozen-lockfile

      - name: Install template dependencies
        working-directory: ./template
        run: |
          yarn install --frozen-lockfile
          npx app-icon init
          npx app-icon generate

      - name: Build apk
        run: |
          cp template/.env.example template/.env
          yarn build-android-e2e

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          avd-name: Nexus_6_API_29
          script: yarn test-android-e2e --take-screenshots all

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots-android
          path: artifacts
          retention-days: 15

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: template/android/app/build/outputs/apk/release/app-release.apk
          retention-days: 15
